moved Snakemake files to top dir

diff --git a/asdMetagen b/asdMetagen
--- a/asdMetagen
+++ b/asdMetagen
@@ -134,11 +134,11 @@ if [[ ! $DOWNLOAD_ONLY ]]; then
 			"${0#./} without the '-d' flag"
 		echo "Exiting..."
 		exit 1
-#	elif [[ ! $FORPRIME ]] || [[ ! $REVPRIME ]]; then
-#		echo "$0: ERROR: Primers missing! Please specify primers with"\
-#			"the '-f' and '-r' flags before re-running"
-#		echo "Exiting..."
-#		exit 1
+	elif [[ ! $FORPRIME ]] || [[ ! $REVPRIME ]]; then
+		echo "$0: ERROR: Primers missing! Please specify primers with"\
+			"the '-f' and '-r' flags before re-running"
+		echo "Exiting..."
+		exit 1
 	fi
 fi
 
@@ -393,20 +393,12 @@ trimLoop(){
 				--discard-untrimmed
 		fi
 
-		if [[ $REVPRIME ]] && [[ $FORPRIME ]]; then
+		if [[ $REVPRIME ]]; then
 			echo "REVPRIME = $REVPRIME"
 			cutadapt -a $REVPRIME\
 				-o $m.trimmed.fasta $m.temp.fasta\
 				--discard-untrimmed
 		fi
-
-		if [[ $REVPRIME ]] && [[ ! $FORPRIME ]]; then
-			echo "REVPRIME = $REVPRIME"
-			cutadapt -a $REVPRIME\
-				-o $m.trimmed.fasta $i\
-				--discard-untrimmed
-		fi
-	
 	done
 	rm -v *.temp.fasta
 	
@@ -421,27 +413,16 @@ offsetTrim(){
 	# 
 	pathTester cutadapt $CUTADAPT_MODULE $CUTADAPT_MOD_VER
 
-	##TODO: Clean up input and output mess in this function
 	# Set input type
-#	in_type=fasta
+	in_type=fasta
 
 	# Move input files to working directory
-#	inPrep trimmed_fastas
-
-	if [[ ! $FORPRIME ]] && [[ ! $REVPRIME ]]; then
-		echo "TEST 1"
-		in_type=fasta
-		inPrep merged_fastas
-	else
-		echo "TEST 2"
-		in_type=trimmed.fasta
-		inPrep trimmed_fastas
-	fi
+	inPrep trimmed_fastas
 
 	for i in ${in_file[@]}; do
-		PRE_OFFSET=${i%.fasta}.preoffset.fasta
-		OFFSET_TEMP=${i%.fasta}.offset.temp.fasta
-		OUTPUT=${i%.fasta}.offset.fasta
+		PRE_OFFSET=${i//trimmed/preoffset}
+		OFFSET_TEMP=${i//trimmed/offset.temp}
+		OUTPUT=${i//trimmed/offset}
 		if [[ $FOR_OFFSET ]] && [[ $REV_OFFSET ]]; then
 			echo "Trimming $FOR_OFFSET nucleotides"\
 				"from 5' end of $i"
@@ -466,17 +447,7 @@ offsetTrim(){
 
 	# Move inputs and outputs back to corresponding directories
 	out_type=offset
-	if [[ ! $FORPRIME ]] && [[ ! $REVPRIME ]]; then
-		outprep merged_fastas offset_fastas
-#		mv *.merged.fasta merged_fastas
-#		mkdir offset_fastas
-#		mv *.offset.fasta offset_fastas
-	else
-		outPrep trimmed_fastas offset_fastas
-#		mv *.trimmed.fasta trimmed_fastas
-#		mkdir offset_fastas
-#		mv *.offset.fasta offset_fastas
-	fi
+	outPrep trimmed_fastas offset_fastas
 }
 
 phixScreen(){
@@ -910,11 +881,7 @@ main(){
 
 	q2aReformat
 	groupFormatter
-
-	# Trim primers
-	if [[ $FORPRIME ]] || [[ $REVPRIME ]]; then
-		trimLoop
-	fi
+	trimLoop
 
 	# Trim nucleotide offset
 	if [[ $FOR_OFFSET ]] || [[ $REV_OFFSET ]]; then
